version: "3.8"

services:
  app:
    image: threatter
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      connection_db_user: ${connection_db_user}
      connection_db_password: ${connection_db_password}
      DB_HOST: ${AWS_DB_HOST}
      DB_PORT: 3306
      DB_USER: ${AWS_DB_USER}
      DB_PASSWORD: ${AWS_DB_PASSWORD}
      DB_NAME: threatter-database

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
